apiVersion: apps/v1
kind: Deployment
metadata:
  name: repo
spec:
  selector:
    matchLabels:
      run: my-repo
  replicas: 1
  template:
    metadata:
      labels:
        run: my-repo
    spec:
      containers:
      - name: repo
        image: library/registry
        ports:
        - containerPort: 5000
        volumeMounts:
        - mountPath: /var/lib/registry
          name: repo-storage
      volumes:
      - name: repo-storage
        hostPath:
          path: /localfs/xyao/k8s/repo/data
