apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
spec:
  containers:
  - name: ubuntu
    image: 10.247.89.29:5000/ubuntu:18.04
    command: [ "/bin/bash", "-ce", "tail -f /dev/null" ]
    ports:
    - containerPort: 22
#  imagePullSecrets:
#    - name: selfregistrykey
