apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
spec:
  containers:
  - name: ubuntu
    image: 10.244.55.4:5000/ubuntu-ddl:v.1.1.2
    command: [ "/bin/bash", "-ce", "tail -f /dev/null" ]
    ports:
    - containerPort: 22
#  imagePullSecrets:
#    - name: selfregistrykey
