apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
spec:
  containers:
  - name: ubuntu
    image: xinyao1994/ubuntu-ddl:v.1.0.0
    command: [ "/bin/bash", "-ce", "tail -f /dev/null" ]  
    ports:
    - containerPort: 22  # here is  
  imagePullSecrets:
    - name: dockerregistrykey
